name: release

on:
  create:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Install additional targets
        run: |
          rustup target add x86_64-unknown-linux-gnu
          rustup target add x86_64-pc-windows-gnu

      - name: Install mingw-w64
        run: sudo apt-get update && sudo apt-get install -y mingw-w64

      - name: Build for Linux
        run: cargo build --release --target x86_64-unknown-linux-gnu

      - name: Build for Windows
        run: cargo build --release --target x86_64-pc-windows-gnu

      - name: Zip binaries
        run: |
          zip -j github-actions-sample-linux-x86_64.zip target/x86_64-unknown-linux-gnu/release/github-actions-sample
          zip -j github-actions-sample-windows-x86_64.zip target/x86_64-pc-windows-gnu/release/github-actions-sample.exe

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          files: |
            github-actions-sample-linux-x86_64.zip
            github-actions-sample-windows-x86_64.zip